### ISSUE TITLE
Notification channels

### ISSUE THREAD

**Issue by towo** [justjanne/QuasselDroid-ng#11]
Since API level 26, [notification channels](https://developer.android.com/guide/topics/ui/notifiers/notifications#ManageChannels) are available for applications; implementing those would allow us to minimize the quasseldroid connected notification, making it now show up alongside actionable notifications.

**Comment by justjanne** [comment]
This has been implemented in the beta (-ng) already, and they are in use. The beta is expected to be released in the next days/weeks, once a few minor bugs have been fixed.
