### ISSUE TITLE
App occasionally pushes new highlight notifications for old highlights

### ISSUE THREAD

**Issue by dabukalam** [justjanne/QuasselDroid-ng#3]
This happens when I first start the app usually, or sometimes when I have it open for a while - I get notifications for queries or highlights that I've already seen in the app.

**Comment by justjanne** [comment]
You probably meant to open this on this repo? https://github.com/sandsmark/QuasselDroid

This is the repo for the preview version of the new alpha, and doesn’t even have notifications yet.

**Comment by dabukalam** [comment]
Ah yes, my apologies. And I see you've already merged a fix!
