### ISSUE TITLE
can't connect to core due to weird servers

### ISSUE THREAD

**Issue by Lemmmy** [justjanne/QuasselDroid-ng#4]
i am trying to connect to my core, which has the osu! irc bridge as a network. this irc bridge isn't fully irc compliant and does a lot of archaic mess, and the user database for it is pretty screwed. however, every quassel client seems to deal with it fine, except quasseldroid-ng.

while connecting, i get several errors, including "InvocationTargetException: null" and this:

![](http://shitty.download/5vBl8m.png)

**Comment by justjanne** [comment]
This message is just a warning, and unrelated to the connection issue.

I’ll fix the connection issue in the next beta-version, but that’ll only be released once the quassel core has implemented the requested features.
