### ISSUE TITLE
Solve Legal Issue

### ISSUE THREAD

**Issue by justjanne** [justjanne/QuasselDroid-ng#5]
The new GitHub TOS requires me to

> grant GitHub a nonexclusive, revocable, worldwide, royalty-free right to (1) use the Content without attribution strictly as necessary to render the Website and provide the Service; and (2) make reasonable adaptations of the Content as provided in this Section. We need these rights to allow basic functions like search to work. 

As the interface declarations are generated from the quassel/quassel project’s header files, they are derived work, and I can not grant this to GitHub without approval from all involved developers.

These are the contributors whose code I reused in QuasselDroid-NG:

- [x] @Sput42 (Manuel Nickschas)
- [x] @egs-me (Marcus Eggenberger)
- [x] @seezer (Sebastian Goth)
- [x] @mamarley (Michael Marley)
- [x] @sandsmark (martin sandsmark)
- [x] @fish-face
- [x] @AlD (Daniel Albers)
- [x] @digitalcircuit (Shane Synan)
- [x] @Nevcairiel (Hendrik Leppkes)
- [x] @jpnurmi (J-P Nurmi)
- [x] @romibi
- [x] @TheOneRing (Hannah von Reth)

Until then, the status of this repo is unclear.

**Comment by MrEgs** [comment]
Of course, you have my approval. Hope you get the necessary replies in a timely manner.

Cheers,
Marcus

**Comment by fish-face** [comment]
My understanding of the GitHub terms indicates that by putting these contributions on GitHub, the right is already granted to developers of forks to do this (Looking at https://help.github.com/articles/github-terms-of-service/#d-user-generated-content subsection 5) because you grant every user the right to fork your (public) repositories, and that right implies granting them the right to grant GitHub the right you refer to.

In any case, I obviously have no issue with this and probably didn't contribute to any of the things you've derived from quassel.

**Comment by jpnurmi** [comment]
+1

**Comment by justjanne** [comment]
@fish-face: That is technically true, but there’s complications.

For example, I didn’t fork through the fork button, so I only have the rights granted to me through the GPL, which don’t allow me to give GitHub these rights.

Also, you added some value to an enum in a header file which I used to auto-generate the relevant enums for my Java code. Which is why you’re listed here :)

**Comment by mamarley** [comment]
You have my approval too.  Thanks for your work on Quasseldroid!

**Comment by fish-face** [comment]
@justjanne Oh, yes, an enum :D. Well, I suppose it depends whether the changes were submitted on GitHub or not, but I see the gap you're referring to.

**Comment by sgoth** [comment]
Sure, please keep up your nice work

**Comment by digitalcircuit** [comment]
Permission's granted!  Not sure if it needs to be extended to the other current Quassel third-party clients, too (I don't think they use generated/derived code); if so, my remark applies to them as well.

Thanks for your work on continuing making mobile chat free and great.

**Comment by sandsmark** [comment]
granted, though I don't like it etc.

:1st_place_medal: :+1:

**Comment by Nevcairiel** [comment]
I agree.

**Comment by romibi** [comment]
It's ok from my side … though i don't think any of my code is really used for quasseldroid-ng

**Comment by Sput42** [comment]
Sure, approved. You using parts of our code to do something cool is surely in the spirit of the GPL, and this project.

**Comment by AlD** [comment]
👍 Approved.

**Comment by TheOneRing** [comment]
Approved
