### ISSUE TITLE
Option for last message instead of channel topic

### ISSUE THREAD

**Issue by Volkor3-16** [justjanne/QuasselDroid-ng#8]
as shown in the image, would be nice to have the option to replace that topic with the latest message sent, much more useful than a really small amount of a topic, along with that, have the icons on the left change in someway to indicate a message sent to the channel.

![image](https://thecum.zone/e7d90c4b67.png)

**Comment by justjanne** [comment]
Please file issues at https://git.kuschku.de/justjanne/Quasseldroid-NG/
